### ISSUE TITLE
Backward Compatibility ke php 7.4

### ISSUE THREAD

**Issue by ivanwilliammd** [ivanwilliammd/satusehat-integration#17]
@YogiPristiawan @SyaefulKai @yudistirasd 
Apakah sdh ada yang pernah cek untuk library ini mungkin bisa backward compatible ke PHP v7.0 / 7.4?

Terimakasih

**Comment by YogiPristiawan** [comment]
Jika ingin backward compatibility ke php v7, sepertinya untuk beberapa sintaks perlu diubah supaya bisa compatible ke PHP v7 pak

**Comment by ivanwilliammd** [comment]
Boleh coba diusulkan untuk syntax yg perlu dirubah untuk backward compatible ke php 7.4? Trims

**Comment by ivanwilliammd** [comment]
UP : @YogiPristiawan 
Note : Boleh dicoba dengan versi tag terbaru v2.1.0 -- in line dengan main per thread comment ini

**Comment by YogiPristiawan** [comment]
Baik pak. setelah weekday yang sangat sibuk, weekend ini coba saya periksa ASAP

**Comment by YogiPristiawan** [comment]
Perlukah mengganti testing tools menjadi PHP Unit pak @ivanwilliammd ?

**Comment by ivanwilliammd** [comment]
Benar @YogiPristiawan , boleh diupdate diupdate dan PR 

https://github.com/ivanwilliammd/satusehat-integration/blob/main/.github/workflows/run-tests.yml
