### ISSUE TITLE
OAuth2Token Create Token ERROR

### ISSUE THREAD

**Issue by revan2159** [ivanwilliammd/satusehat-integration#49]
**Describe the bug**
Attempt to read property "issue" on null
} catch (ClientException $e) {
            $res = json_decode($e->getResponse()->getBody()->getContents());
            **$issue_information = $res->issue[0]->details->text;  // NULL**
            $this->log($issue_information, 'POST Token', $url, null, (array) $res);
            return false;
        }

**Comment by revan2159** [comment]
# Error hilang jika 
public function token()
    {
        $token = SatusehatToken::where('environment', $this->satusehat_env)->where('client_id', $this->client_id)->orderBy('created_at', 'desc')
            ->where('created_at', '>', now()->subMinutes(50))->first();

        if ($token) {
            return $token->token;
        }

        $client = new Client();

        $headers = [
            **'User-Agent' => 'PostmanRuntime/7.37.3',**
            'Content-Type' => 'application/x-www-form-urlencoded',
        ];
        $options = [
            'form_params' => [
                'client_id' => $this->client_id,
                'client_secret' => $this->client_secret,
            ],
        ];

        // Create session
        $url = $this->auth_url . '/accesstoken?grant_type=client_credentials';
        $request = new Request('POST', $url, $headers);

        try {
            $res = $client->sendAsync($request, $options)->wait();
            $contents = json_decode($res->getBody()->getContents());

            if (isset($contents->access_token)) {
                SatusehatToken::create([
                    'environment' => $this->satusehat_env,
                    'client_id' => $this->client_id,
                    'token' => $contents->access_token,
                ]);

                return $contents->access_token;
            } else {
                return $this->respondError($this->oauth2_error);
            }
        } catch (ClientException $e) {
            // error.
            $res = json_decode($e->getResponse()->getBody()->getContents());
            $issue_information = $res->issue[0]->details->text;

            $this->log($issue_information, 'POST Token', $url, null, (array) $res);

            return $issue_information;
        }
    }

**Comment by SyaefulKai** [comment]
Error tsb bisa terjadi karena nilai $res->issue[0] bernilai NULL, yang dimana seharusnya $res->issue[0] ini berisikan pesan error dari request.
![Screenshot 2024-05-04 164034](https://github.com/ivanwilliammd/satusehat-integration/assets/158563298/0827e4fb-93d8-4250-93cc-50a32b352bb8)

**Comment by revan2159** [comment]
tapi respon nya tu 403 

![image](https://github.com/ivanwilliammd/satusehat-integration/assets/64825576/980110f6-fb1d-490a-980e-6bd719620c9e)

**Comment by revan2159** [comment]
error nya hilang jika 

`$headers = [
            'User-Agent' => 'PostmanRuntime/7.37.3',
            'Content-Type' => 'application/x-www-form-urlencoded'
        ];`

**Comment by ivanwilliammd** [comment]
Saya tutup issue ini, karena temuan ini invalid. saran saya coba perhatikan apakah : 
1. Internet / server hosting yg digunakan merupakan provider Indonesia, karena biasanya kalau tdk muncul error, bisa saja kena geoblocking
2. Ada kemungkinan kelebihan extraspace pada client ID & client secret sehingga throwing error
